# Python CircleCI 2.0 configuration file
version: 3.1
jobs:
  one:
    docker:
      - image: circleci/python:3.7
    steps:
      # Step 1: obtain repo from GitHub
      - checkout
      # Step 2: create virtual env and install dependencies
      - run:
          name: install dependencies
          command: |
            python3 -m venv main
            pip install -r requirements.txt
      # Step 3: run linter and tests
      - run:
          name: run tests
          command: |
            pytest -v --cov
workflows:
  version:2
  one_workflow:
    jobs:
      - one